# Generated by Django 5.1.3 on 2025-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE', 'percentage'), ('FIXED', 'fixed'), ('FREE_SHIPPING', 'free shipping'), ('BUY_ONE_GET_ONE', 'buy one get one')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE', 'percentage'), ('FIXED', 'fixed'), ('FREE_SHIPPING', 'free shipping'), ('BUY_ONE_GET_ONE', 'buy one get one')], max_length=50),
        ),
    ]
