# Generated by Django 5.1.3 on 2025-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_coupon_type_alter_coupon_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed'), ('free shipping', 'free shipping'), ('buy one get one', 'buy one get one')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('percentage', 'percentage'), ('fixed', 'fixed'), ('free shipping', 'free shipping'), ('buy one get one', 'buy one get one')], max_length=50),
        ),
    ]
