# Generated by Django 5.1.3 on 2025-04-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.province'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='province_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.province'),
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.district'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='ward_commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.ward'),
        ),
    ]
