# Generated by Django 5.1.3 on 2025-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='speciic_address',
            new_name='specific_address',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
