# Generated by Django 5.1.3 on 2025-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
