# Generated by Django 5.1.3 on 2025-05-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_color_orderitem_sale_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
