# Generated by Django 5.1.3 on 2025-05-04 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_speciic_address_deliveryaddress_specific_address_and_more'),
        ('order', '0006_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_info',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='address.deliveryaddress'),
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
    ]
