# Generated by Django 5.1.3 on 2025-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/'),
        ),
    ]
